/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

//Directivas (parámetros generales) para definir un identificador que el compilador utilizará
#ifndef _BITACORA_H_RPCGEN
#define _BITACORA_H_RPCGEN

//Importación de librerías RPC
#include <rpc/rpc.h>

//Establecer compatibilidad con C/C++
#ifdef __cplusplus
extern "C" {
#endif

//Estructura necesaria definida en bitacora.x que usaran el cliente-servidor para serialización
struct String {
	char opt[6];
	char name[50];
};
typedef struct String String;

//Directivas para definir un id único del programa en hex y la versión de la suma
#define BITACORA_PROG 0x23451111
#define BITACORA_VERS 1

//En caso de ser codigo C/C++
#if defined(__STDC__) || defined(__cplusplus)
//Operación 1 de nuestro programa
#define ADD 1
extern  char ** add_1(char **, CLIENT *);					//Interfaz stub del cliente
extern  char ** add_1_svc(char **, struct svc_req *);				//Procedimiento recomoto del servidor
//Operación 2 de nuestro programa
#define SEARCH 2
extern  char ** search_1(char **, CLIENT *);					//Interfaz stub del cliente
extern  char ** search_1_svc(char **, struct svc_req *);			//Procedimiento recomoto del servidor
extern int bitacora_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);		//Resultado dada la versión de nuestro programa

#else /* Para cualquier otra versión de C: K&R C */
#define ADD 1
extern  char ** add_1();		//Interfaz stub del cliente	
extern  char ** add_1_svc();		//Procedimiento recomoto del servidor	
#define SEARCH 2
extern  char ** search_1();		//Interfaz stub del cliente	
extern  char ** search_1_svc();		//Procedimiento recomoto del servidor
extern int bitacora_prog_1_freeresult ();	//Resultado dada la versión de nuestro programa
#endif /* K&R C */

/* the xdr functions */
//Checamos la consistencia de la estructura enviada con xdr_intpair
#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_String (XDR *, String*);

#else /* Para cualquier otra versión de C: K&R C */
extern bool_t xdr_String ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BITACORA_H_RPCGEN */
